version: "3"

services:
  app:
    container_name: app
    build: .
    command: ["gunicorn", "shop.wsgi:application", "--workers", "3", "--bind", "0.0.0.0:8000"]
    ports:
      - "8000:8000"

  nginx:
    container_name: nginx
    build: nginx
    ports:
      - "80:80"
    depends_on:
      - app
    logging:
      driver: "local"
